[phases.setup]
nixPkgs = ["python313", "python313Packages.pip", "python313Packages.virtualenv"]

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    ". /opt/venv/bin/activate && pip install --upgrade pip",
    ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Build phase: skipping collectstatic (will run at startup with DB access)'"]

[start]
cmd = ".\/opt\/venv\/bin\/activate && sh startup.sh"
