[phases.setup]
nixPkgs = ["python313", "gcc", "pkg-config", "default-mysqlclient"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "gunicorn medical_shop.wsgi --bind 0.0.0.0:$PORT"
