[phases.setup]
nixPkgs = ["python313", "python313Packages.pip", "python313Packages.virtualenv"]

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    ". /opt/venv/bin/activate && pip install --upgrade pip",
    ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = [". /opt/venv/bin/activate && python manage.py collectstatic --noinput"]

[start]
cmd = ". /opt/venv/bin/activate && gunicorn medical_shop.wsgi --bind 0.0.0.0:$PORT"
