[phases.setup]
nixPkgs = ["python313", "python313Packages.pip", "python313Packages.virtualenv", "gcc", "pkg-config", "mariadb-connector-c", "openssl", "zlib"]

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    ". /opt/venv/bin/activate && pip install --upgrade pip",
    ". /opt/venv/bin/activate && PKG_CONFIG_PATH=${mariadb-connector-c}/lib/pkgconfig pip install -r requirements.txt"
]

[phases.build]
cmds = [". /opt/venv/bin/activate && python manage.py collectstatic --noinput"]

[start]
cmd = ". /opt/venv/bin/activate && gunicorn medical_shop.wsgi --bind 0.0.0.0:$PORT"
